import { AlertTriangle } from 'lucide-react'
import { TopBar } from './TopBar'
import { LeftPanel } from './LeftPanel'
import { CenterCanvas } from './CenterCanvas'
import { RightPanel } from './RightPanel'
import { ThemeToggle } from './ThemeToggle'

/**
 * Main Layout for Postloom
 * Implements the "Soft Dashboard" aesthetic:
 * - Global soft gray/slate-50 background
 * - Sections float as distinct elements
 * - Clean separation of concerns
 */
export function TweetStudioLayout() {
    return (
        <div className="flex h-screen w-full flex-col bg-slate-50 dark:bg-[#0f1117] overflow-hidden text-slate-900 dark:text-slate-100 font-sans transition-colors duration-300">
            {/* Top Bar - Floating header with glassmorphism effect */}
            <TopBar />

            {/* Main Workspace Area */}
            <main className="flex flex-1 overflow-hidden">
                {/* Left Sidebar - Navigation & Content */}
                <LeftPanel />

                {/* Center Stage - The "Canvas" */}
                <div className="flex-1 flex flex-col min-w-0 relative z-10">
                    <CenterCanvas />
                </div>

                {/* Right Sidebar - Design Controls */}
                <RightPanel />
            </main>

            {/* Legal Disclaimer Footer */}
            <footer className="shrink-0 border-t border-slate-200 dark:border-slate-800 bg-white/50 dark:bg-slate-900/50 backdrop-blur-sm">
                <div className="flex items-center justify-center gap-2 px-4 py-2">
                    <AlertTriangle className="h-3.5 w-3.5 text-amber-500 shrink-0" />
                    <p className="text-[10px] text-slate-600 dark:text-slate-400 text-center">
                        <span className="font-medium">Legal Disclaimer:</span> This tweet was created using Postloom. 
                        The content is generated by the user and is not affiliated with or endorsed by Twitter/X. 
                        Users are responsible for ensuring their content complies with all applicable laws and platform terms of service.
                    </p>
                </div>
            </footer>
        </div>
    )
}

export { ThemeToggle }
